name: My First Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-refs/pull/1/merge
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [3.13 , 3.12, 2.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install requests

      - name: Print a message to the console
        run: echo "¡Hola desde GitHub Actions!"
 
      - name: Run Script
        run: python ./src/main.py

    
